# Change these first
owner: Modern-Modpacks # Your GitHub organization or username, where this repository lives
repo: mm-upptime # The name of this repository

sites:
  - name: MissingTexture
    url: https://missingtexture.modernmodpacks.site
    icon: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/Icons/Other/missingtexture.png
  - name: KJSPKG Statistics (Automatin')
    assignees:
      - tizu69
    url: https://tizudev.vercel.app/automatin/api/1025316079226064966/kjspkg
    icon: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/Icons/Other/kjspkg.png
  - name: ThisRecipeDoesNotExist
    url: https://thisrecipedoesnotexist.modernmodpacks.site
    icon: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/Icons/Other/missingtexture.png
  - name: Splashes
    url: https://splashes.modernmodpacks.site

status-website:
  logoUrl: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/rounded_logo.png
  favicon: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/rounded_logo.png
  theme: night
  css: ".icon { border-radius: 50% }"

  cname: status.modernmodpacks.site
  
  name: MM Status
  introTitle: "**This is a montioring page for projects made by [Modern Modpacks](https://modernmodpacks.site)**"
  introMessage: If you see anything go offline, please report it to [our discord server](https://discord.modernmodpacks.site)

  navbar:
    - title: Status
      href: /
    - title: Source
      href: https://github.com/Modern-Modpacks/mm-upptime
    - title: Website
      href: https://modernmodpacks.site
    - title: Discord
      href: https://discord.modernmodpacks.site
