# Change these first
owner: Modern-Modpacks # Your GitHub organization or username, where this repository lives
repo: mm-upptime # The name of this repository

sites:
  - name: MissingTexture
    url: https://missingtexture.modernmodpacks.site
    icon: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/Icons/Other/missingtexture.png
  - name: KJSPKG Statistics
    url: https://tizudev.vercel.app/automatin/api/1025316079226064966/kjspkg
    icon: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/Icons/Other/kjspkg.png
  - name: ThisRecipeDoesNotExist
    url: https://thisrecipedoesnotexist.modernmodpacks.site
    icon: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/Icons/Other/missingtexture.png
  - name: Splashes
    url: https://splashes.modernmodpacks.site

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.modernmodpacks.site
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/rounded_logo.png
  favicon: https://raw.githubusercontent.com/Modern-Modpacks/assets/main/rounded_logo.png
  name: MM Status
  introTitle: "**This is a montioring page for projects made by [Modern Modpacks](https://modernmodpacks.site)**"
  introMessage: If you see anything go offline, please report it to [our discord server](https://discord.modernmodpacks.site)
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://modernmodpacks.site
    - title: Discord
      href: https://discord.modernmodpacks.site

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
